/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_fftdemo_testfft */

#ifndef _Included_com_example_fftdemo_testfft
#define _Included_com_example_fftdemo_testfft
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_fftdemo_testfft
 * Method:    testfft2d
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_fftdemo_testfft_testfft2d
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
